// ============================================================
// SECTION 1: THE 500-ELEMENT VOCABULARY
// Each element: { id, domain, tags, props? }
// ============================================================

export interface Element {
  id: string;
  domain: string;
  tags: string[];
  props?: Record<string, number>;
}

export const ELEMENTS: Element[] = [
  // --- BODY_STRUCTURE (~60) ---
  { id: 'head_lion', domain: 'BODY_STRUCTURE', tags: ['predator', 'mammal', 'mane_capable'] },
  { id: 'head_wolf', domain: 'BODY_STRUCTURE', tags: ['predator', 'mammal', 'pack'] },
  { id: 'head_eagle', domain: 'BODY_STRUCTURE', tags: ['avian', 'predator', 'beak'] },
  { id: 'head_boar', domain: 'BODY_STRUCTURE', tags: ['mammal', 'tusked', 'herbivore'] },
  { id: 'head_serpent', domain: 'BODY_STRUCTURE', tags: ['reptile', 'venom_capable', 'elongated'] },
  { id: 'head_horned', domain: 'BODY_STRUCTURE', tags: ['mammal', 'horned', 'herbivore'] },
  { id: 'head_humanoid', domain: 'BODY_STRUCTURE', tags: ['humanoid', 'expressive', 'tool_user'] },
  { id: 'head_canine', domain: 'BODY_STRUCTURE', tags: ['mammal', 'predator', 'keen_smell'] },
  { id: 'head_feline', domain: 'BODY_STRUCTURE', tags: ['mammal', 'predator', 'night_hunter'] },
  { id: 'head_rodent', domain: 'BODY_STRUCTURE', tags: ['mammal', 'small', 'gnawing'] },
  { id: 'body_snake', domain: 'BODY_STRUCTURE', tags: ['elongated', 'limbless', 'flexible'] },
  { id: 'body_quadruped', domain: 'BODY_STRUCTURE', tags: ['quadruped', 'stable', 'runner'] },
  { id: 'body_biped', domain: 'BODY_STRUCTURE', tags: ['biped', 'hands_free', 'tool_user'] },
  { id: 'body_avian', domain: 'BODY_STRUCTURE', tags: ['avian', 'lightweight', 'hollow_bone'] },
  { id: 'body_insectoid', domain: 'BODY_STRUCTURE', tags: ['insectoid', 'exoskeleton', 'multi_limb'] },
  { id: 'body_aquatic', domain: 'BODY_STRUCTURE', tags: ['aquatic', 'streamlined', 'gilled'] },
  { id: 'body_humanoid', domain: 'BODY_STRUCTURE', tags: ['humanoid', 'versatile', 'endurance'] },
  { id: 'body_amphibious', domain: 'BODY_STRUCTURE', tags: ['amphibious', 'moist_skin', 'dual_breath'] },
  { id: 'limb_leg', domain: 'BODY_STRUCTURE', tags: ['locomotion', 'weight_bearing'] },
  { id: 'limb_arm', domain: 'BODY_STRUCTURE', tags: ['manipulation', 'dexterity'] },
  { id: 'limb_wing_small', domain: 'BODY_STRUCTURE', tags: ['flight', 'small_wing', 'gliding'], props: { wing_area: 0.3, lift: 0.2 } },
  { id: 'limb_wing_large', domain: 'BODY_STRUCTURE', tags: ['flight', 'large_wing', 'powered'], props: { wing_area: 0.9, lift: 0.8 } },
  { id: 'limb_tentacle', domain: 'BODY_STRUCTURE', tags: ['manipulation', 'flexible', 'prehensile'] },
  { id: 'limb_fin', domain: 'BODY_STRUCTURE', tags: ['aquatic', 'propulsion'] },
  { id: 'tail_long', domain: 'BODY_STRUCTURE', tags: ['balance', 'communication', 'prehensile_capable'] },
  { id: 'tail_club', domain: 'BODY_STRUCTURE', tags: ['weapon', 'blunt_force', 'defense'] },
  { id: 'tail_fan', domain: 'BODY_STRUCTURE', tags: ['display', 'communication', 'thermoregulation'] },
  { id: 'neck_long', domain: 'BODY_STRUCTURE', tags: ['reach', 'vulnerable', 'high_vantage'] },
  { id: 'neck_thick', domain: 'BODY_STRUCTURE', tags: ['armor', 'strong', 'limited_rotation'] },
  { id: 'shell', domain: 'BODY_STRUCTURE', tags: ['armor', 'defense', 'slow'] },
  { id: 'spine_ridge', domain: 'BODY_STRUCTURE', tags: ['display', 'intimidation', 'defense'] },
  { id: 'horn_curved', domain: 'BODY_STRUCTURE', tags: ['weapon', 'display', 'combat'] },
  { id: 'horn_straight', domain: 'BODY_STRUCTURE', tags: ['weapon', 'charging', 'combat'] },
  { id: 'antler', domain: 'BODY_STRUCTURE', tags: ['display', 'combat', 'seasonal'] },
  { id: 'tusk', domain: 'BODY_STRUCTURE', tags: ['weapon', 'digging', 'display'] },
  { id: 'claw_hooked', domain: 'BODY_STRUCTURE', tags: ['weapon', 'climbing', 'tearing'] },
  { id: 'claw_flat', domain: 'BODY_STRUCTURE', tags: ['digging', 'running', 'traction'] },
  { id: 'fang', domain: 'BODY_STRUCTURE', tags: ['weapon', 'piercing', 'predator'] },
  { id: 'beak', domain: 'BODY_STRUCTURE', tags: ['weapon', 'manipulation', 'avian'] },
  { id: 'mandible', domain: 'BODY_STRUCTURE', tags: ['weapon', 'crushing', 'insectoid'] },
  { id: 'hoof', domain: 'BODY_STRUCTURE', tags: ['locomotion', 'running', 'hard_surface'] },
  { id: 'paw', domain: 'BODY_STRUCTURE', tags: ['locomotion', 'stealth', 'climbing'] },
  { id: 'talon', domain: 'BODY_STRUCTURE', tags: ['weapon', 'grasping', 'avian'] },
  { id: 'fin_dorsal', domain: 'BODY_STRUCTURE', tags: ['stability', 'aquatic', 'display'] },
  { id: 'fin_tail', domain: 'BODY_STRUCTURE', tags: ['propulsion', 'aquatic', 'maneuver'] },
  { id: 'gills', domain: 'BODY_STRUCTURE', tags: ['aquatic', 'breathing', 'water_dependent'] },
  { id: 'trunk', domain: 'BODY_STRUCTURE', tags: ['manipulation', 'reach', 'sensitive'] },
  { id: 'mane', domain: 'BODY_STRUCTURE', tags: ['display', 'intimidation', 'neck_protection'] },
  { id: 'crest', domain: 'BODY_STRUCTURE', tags: ['display', 'communication', 'species_id'] },
  { id: 'frill', domain: 'BODY_STRUCTURE', tags: ['display', 'intimidation', 'thermoregulation'] },
  { id: 'dewlap', domain: 'BODY_STRUCTURE', tags: ['display', 'communication', 'thermoregulation'] },
  { id: 'pouch', domain: 'BODY_STRUCTURE', tags: ['carrying', 'young_protection', 'marsupial'] },
  { id: 'body_massive', domain: 'BODY_STRUCTURE', tags: ['heavy', 'strong', 'slow'], props: { mass: 0.9 } },
  { id: 'body_small', domain: 'BODY_STRUCTURE', tags: ['light', 'agile', 'fast'], props: { mass: 0.1 } },
  { id: 'body_medium', domain: 'BODY_STRUCTURE', tags: ['balanced', 'versatile'], props: { mass: 0.5 } },
  { id: 'head_cetacean', domain: 'BODY_STRUCTURE', tags: ['aquatic', 'mammal', 'echolocation'] },
  { id: 'head_ungulate', domain: 'BODY_STRUCTURE', tags: ['herbivore', 'grazing', 'herd'] },
  { id: 'body_arachnid', domain: 'BODY_STRUCTURE', tags: ['arachnid', 'multi_limb', 'web_capable'] },
  { id: 'limb_clawed_arm', domain: 'BODY_STRUCTURE', tags: ['weapon', 'manipulation', 'predator'] },
  { id: 'body_crustacean', domain: 'BODY_STRUCTURE', tags: ['armored', 'aquatic', 'multi_limb'] },

  // --- SURFACE (~25) ---
  { id: 'fur_short', domain: 'SURFACE', tags: ['insulation', 'mammal', 'camouflage_capable'] },
  { id: 'fur_long', domain: 'SURFACE', tags: ['insulation_heavy', 'mammal', 'display'] },
  { id: 'scales_fine', domain: 'SURFACE', tags: ['protection', 'reptile', 'streamlined'] },
  { id: 'scales_plate', domain: 'SURFACE', tags: ['armor', 'reptile', 'heavy'] },
  { id: 'feathers', domain: 'SURFACE', tags: ['insulation', 'avian', 'flight_assist', 'display'] },
  { id: 'chitin', domain: 'SURFACE', tags: ['armor', 'insectoid', 'lightweight'] },
  { id: 'hide_thick', domain: 'SURFACE', tags: ['armor', 'mammal', 'durable'] },
  { id: 'skin_smooth', domain: 'SURFACE', tags: ['sensitive', 'aquatic', 'vulnerable'] },
  { id: 'spines', domain: 'SURFACE', tags: ['defense', 'intimidation', 'pain'] },
  { id: 'moss_growth', domain: 'SURFACE', tags: ['camouflage', 'slow', 'symbiotic'] },
  { id: 'slime_coat', domain: 'SURFACE', tags: ['slippery', 'aquatic', 'toxin_barrier'] },
  { id: 'bark_skin', domain: 'SURFACE', tags: ['armor', 'plant', 'camouflage'] },
  { id: 'crystal_growth', domain: 'SURFACE', tags: ['defense', 'reflective', 'rare'] },
  { id: 'quill_coverage', domain: 'SURFACE', tags: ['defense', 'pain', 'mammal'] },
  { id: 'mottled_skin', domain: 'SURFACE', tags: ['camouflage', 'amphibious', 'moisture'] },
  { id: 'iridescent_scales', domain: 'SURFACE', tags: ['display', 'confusion', 'aquatic'] },
  { id: 'wool_growth', domain: 'SURFACE', tags: ['insulation', 'shearable', 'domestic'] },
  { id: 'leathery_skin', domain: 'SURFACE', tags: ['protection', 'durable', 'reptile'] },
  { id: 'gelatinous_body', domain: 'SURFACE', tags: ['shapeless', 'regeneration', 'aquatic'] },
  { id: 'ashen_fur', domain: 'SURFACE', tags: ['camouflage', 'insulation', 'volcanic'] },
  { id: 'velvet_fur', domain: 'SURFACE', tags: ['sensitive', 'luxury', 'soft'] },
  { id: 'oily_coat', domain: 'SURFACE', tags: ['waterproof', 'aquatic', 'slippery'] },
  { id: 'porous_skin', domain: 'SURFACE', tags: ['absorption', 'breathing', 'vulnerable'] },
  { id: 'metallic_shell', domain: 'SURFACE', tags: ['armor_heavy', 'conductive', 'rare'] },
  { id: 'translucent_skin', domain: 'SURFACE', tags: ['camouflage', 'deep_sea', 'fragile'] },

  // --- BIOLOGY_ORGAN (~50) ---
  { id: 'venom_gland', domain: 'BIOLOGY_ORGAN', tags: ['weapon', 'poison', 'predator'] },
  { id: 'lungs_large', domain: 'BIOLOGY_ORGAN', tags: ['endurance', 'stamina', 'oxygen'] },
  { id: 'heart_efficient', domain: 'BIOLOGY_ORGAN', tags: ['stamina', 'recovery', 'burst'] },
  { id: 'stomach_ruminant', domain: 'BIOLOGY_ORGAN', tags: ['herbivore', 'efficient_digestion', 'slow'] },
  { id: 'liver_toxin_resist', domain: 'BIOLOGY_ORGAN', tags: ['resistance', 'detox', 'scavenger'] },
  { id: 'fat_reserve', domain: 'BIOLOGY_ORGAN', tags: ['survival', 'insulation', 'hibernation'] },
  { id: 'bone_dense', domain: 'BIOLOGY_ORGAN', tags: ['strength', 'heavy', 'impact_resist'] },
  { id: 'bone_hollow', domain: 'BIOLOGY_ORGAN', tags: ['lightweight', 'avian', 'fragile'] },
  { id: 'muscle_fast_twitch', domain: 'BIOLOGY_ORGAN', tags: ['speed', 'burst', 'predator'] },
  { id: 'muscle_endurance', domain: 'BIOLOGY_ORGAN', tags: ['stamina', 'persistence', 'prey'] },
  { id: 'electric_organ', domain: 'BIOLOGY_ORGAN', tags: ['weapon', 'stun', 'aquatic'] },
  { id: 'ink_sac', domain: 'BIOLOGY_ORGAN', tags: ['defense', 'escape', 'aquatic'] },
  { id: 'bioluminescent', domain: 'BIOLOGY_ORGAN', tags: ['communication', 'lure', 'deep_sea'] },
  { id: 'regenerative_tissue', domain: 'BIOLOGY_ORGAN', tags: ['healing', 'limb_recovery', 'slow'] },
  { id: 'acid_gland', domain: 'BIOLOGY_ORGAN', tags: ['weapon', 'corrosion', 'defense'] },
  { id: 'silk_spinner', domain: 'BIOLOGY_ORGAN', tags: ['web', 'binding', 'construction'] },
  { id: 'fire_gland', domain: 'BIOLOGY_ORGAN', tags: ['weapon', 'rare', 'intimidation'] },
  { id: 'ice_gland', domain: 'BIOLOGY_ORGAN', tags: ['weapon', 'rare', 'freezing'] },
  { id: 'pheromone_gland', domain: 'BIOLOGY_ORGAN', tags: ['communication', 'mating', 'marking'] },
  { id: 'echo_chamber', domain: 'BIOLOGY_ORGAN', tags: ['echolocation', 'navigation', 'cave'] },
  { id: 'thermal_pit', domain: 'BIOLOGY_ORGAN', tags: ['infrared', 'hunting', 'nocturnal'] },
  { id: 'multi_chamber_heart', domain: 'BIOLOGY_ORGAN', tags: ['stamina', 'diving', 'pressure'] },
  { id: 'water_storage', domain: 'BIOLOGY_ORGAN', tags: ['desert', 'survival', 'endurance'] },
  { id: 'spore_producer', domain: 'BIOLOGY_ORGAN', tags: ['reproduction', 'defense', 'plant'] },
  { id: 'photosynthetic_skin', domain: 'BIOLOGY_ORGAN', tags: ['energy', 'sun', 'slow'] },
  { id: 'symbiotic_bacteria', domain: 'BIOLOGY_ORGAN', tags: ['digestion', 'immunity', 'mutual'] },
  { id: 'venom_delivery_fang', domain: 'BIOLOGY_ORGAN', tags: ['weapon', 'poison', 'injection'] },
  { id: 'stinger', domain: 'BIOLOGY_ORGAN', tags: ['weapon', 'poison', 'insectoid'] },
  { id: 'spray_gland', domain: 'BIOLOGY_ORGAN', tags: ['defense', 'repellent', 'noxious'] },
  { id: 'glow_organ', domain: 'BIOLOGY_ORGAN', tags: ['communication', 'lure', 'warning'] },
  { id: 'adrenaline_surge', domain: 'BIOLOGY_ORGAN', tags: ['burst', 'fear_response', 'strength'] },
  { id: 'slow_metabolism', domain: 'BIOLOGY_ORGAN', tags: ['efficiency', 'longevity', 'low_food'] },
  { id: 'fast_metabolism', domain: 'BIOLOGY_ORGAN', tags: ['energy', 'hunger', 'active'] },
  { id: 'blood_clotting', domain: 'BIOLOGY_ORGAN', tags: ['healing', 'survival', 'wound'] },
  { id: 'temperature_regulation', domain: 'BIOLOGY_ORGAN', tags: ['homeostasis', 'endure', 'climate'] },
  { id: 'magnetic_organ', domain: 'BIOLOGY_ORGAN', tags: ['navigation', 'migration', 'sensing'] },
  { id: 'pressure_resistance', domain: 'BIOLOGY_ORGAN', tags: ['deep_sea', 'structural', 'survival'] },
  { id: 'radiation_resist', domain: 'BIOLOGY_ORGAN', tags: ['extreme', 'repair', 'rare'] },
  { id: 'parasite_defense', domain: 'BIOLOGY_ORGAN', tags: ['immunity', 'grooming', 'health'] },
  { id: 'brood_pouch', domain: 'BIOLOGY_ORGAN', tags: ['reproduction', 'protection', 'carrying'] },
  { id: 'egg_layer', domain: 'BIOLOGY_ORGAN', tags: ['reproduction', 'oviparous', 'nesting'] },
  { id: 'live_birth', domain: 'BIOLOGY_ORGAN', tags: ['reproduction', 'mammal', 'nurturing'] },
  { id: 'filter_feeder', domain: 'BIOLOGY_ORGAN', tags: ['feeding', 'aquatic', 'passive'] },
  { id: 'ambush_stomach', domain: 'BIOLOGY_ORGAN', tags: ['feeding', 'large_meal', 'predator'] },
  { id: 'venom_immunity', domain: 'BIOLOGY_ORGAN', tags: ['resistance', 'immunity', 'predator_eater'] },
  { id: 'calcium_deposit', domain: 'BIOLOGY_ORGAN', tags: ['armor', 'structure', 'growth'] },
  { id: 'oxygen_storage', domain: 'BIOLOGY_ORGAN', tags: ['diving', 'endurance', 'aquatic'] },
  { id: 'healing_factor', domain: 'BIOLOGY_ORGAN', tags: ['regeneration', 'fast', 'rare'] },
  { id: 'toxin_synthesis', domain: 'BIOLOGY_ORGAN', tags: ['poison', 'defense', 'chemical'] },
  { id: 'digestive_acid', domain: 'BIOLOGY_ORGAN', tags: ['digestion', 'defense', 'corrosion'] },

  // --- SENSE (~35) ---
  { id: 'night_vision', domain: 'SENSE', tags: ['vision', 'nocturnal', 'predator'] },
  { id: 'echolocation', domain: 'SENSE', tags: ['sonar', 'navigation', 'cave'] },
  { id: 'keen_smell', domain: 'SENSE', tags: ['olfactory', 'tracking', 'predator'] },
  { id: 'thermal_sense', domain: 'SENSE', tags: ['infrared', 'hunting', 'nocturnal'] },
  { id: 'tremor_sense', domain: 'SENSE', tags: ['vibration', 'burrowing', 'ground'] },
  { id: 'magnetic_sense', domain: 'SENSE', tags: ['navigation', 'migration', 'orientation'] },
  { id: 'color_vision', domain: 'SENSE', tags: ['vision', 'detail', 'diurnal'] },
  { id: 'wide_field_vision', domain: 'SENSE', tags: ['vision', 'prey', 'awareness'] },
  { id: 'keen_hearing', domain: 'SENSE', tags: ['auditory', 'communication', 'alert'] },
  { id: 'taste_toxin_detection', domain: 'SENSE', tags: ['gustatory', 'safety', 'foraging'] },
  { id: 'electroreception', domain: 'SENSE', tags: ['electric', 'aquatic', 'hunting'] },
  { id: 'pressure_sense', domain: 'SENSE', tags: ['lateral_line', 'aquatic', 'movement'] },
  { id: 'polarized_vision', domain: 'SENSE', tags: ['navigation', 'sky', 'avian'] },
  { id: 'ultraviolet_vision', domain: 'SENSE', tags: ['vision', 'flowers', 'patterns'] },
  { id: 'infrasound_hearing', domain: 'SENSE', tags: ['long_range', 'communication', 'large'] },
  { id: 'ultrasound_hearing', domain: 'SENSE', tags: ['short_range', 'echolocation', 'small'] },
  { id: 'motion_detection', domain: 'SENSE', tags: ['vision', 'predator', 'prey'] },
  { id: 'chemical_trail', domain: 'SENSE', tags: ['olfactory', 'tracking', 'social'] },
  { id: 'depth_perception', domain: 'SENSE', tags: ['vision', 'predator', 'accuracy'] },
  { id: 'light_polarization', domain: 'SENSE', tags: ['navigation', 'water', 'insect'] },
  { id: 'balance_sense', domain: 'SENSE', tags: ['vestibular', 'agility', 'climbing'] },
  { id: 'pain_tolerance', domain: 'SENSE', tags: ['endurance', 'combat', 'survival'] },
  { id: 'proprioception', domain: 'SENSE', tags: ['body_awareness', 'agility', 'coordination'] },
  { id: 'time_sense', domain: 'SENSE', tags: ['circadian', 'migration', 'seasonal'] },
  { id: 'humidity_sense', domain: 'SENSE', tags: ['weather', 'water', 'amphibious'] },
  { id: 'sound_localization', domain: 'SENSE', tags: ['auditory', 'direction', 'predator'] },
  { id: 'taste_sweet', domain: 'SENSE', tags: ['gustatory', 'energy', 'fruit'] },
  { id: 'taste_bitter', domain: 'SENSE', tags: ['gustatory', 'toxin', 'warning'] },
  { id: 'near_field_vision', domain: 'SENSE', tags: ['vision', 'close', 'detail'] },
  { id: 'far_field_vision', domain: 'SENSE', tags: ['vision', 'distance', 'scouting'] },
  { id: 'vibration_sense', domain: 'SENSE', tags: ['web', 'spider', 'detection'] },
  { id: 'temperature_sense', domain: 'SENSE', tags: ['thermal', 'environment', 'comfort'] },
  { id: 'social_recognition', domain: 'SENSE', tags: ['faces', 'individual', 'social'] },
  { id: 'danger_sense', domain: 'SENSE', tags: ['intuition', 'prey', 'survival'] },
  { id: 'spatial_memory', domain: 'SENSE', tags: ['navigation', 'caching', 'territory'] },

  // --- INSTINCT (~45) ---
  { id: 'pack_instinct', domain: 'INSTINCT', tags: ['social', 'cooperation', 'hunting'] },
  { id: 'territorial', domain: 'INSTINCT', tags: ['aggression', 'defense', 'solitary'] },
  { id: 'nesting', domain: 'INSTINCT', tags: ['shelter', 'young', 'preparation'] },
  { id: 'migratory', domain: 'INSTINCT', tags: ['movement', 'seasonal', 'navigation'] },
  { id: 'hoarding', domain: 'INSTINCT', tags: ['accumulation', 'preparation', 'greed'] },
  { id: 'ambush', domain: 'INSTINCT', tags: ['patience', 'predator', 'stealth'] },
  { id: 'playful', domain: 'INSTINCT', tags: ['social', 'learning', 'young'] },
  { id: 'curious', domain: 'INSTINCT', tags: ['exploration', 'learning', 'risk'] },
  { id: 'fearful_of_fire', domain: 'INSTINCT', tags: ['avoidance', 'survival', 'learned'] },
  { id: 'cannibalistic', domain: 'INSTINCT', tags: ['predator', 'same_species', 'rare'] },
  { id: 'nocturnal', domain: 'INSTINCT', tags: ['night', 'activity', 'hiding'] },
  { id: 'hibernating', domain: 'INSTINCT', tags: ['winter', 'rest', 'fat'] },
  { id: 'imprinting', domain: 'INSTINCT', tags: ['bonding', 'young', 'parent'] },
  { id: 'mimicry', domain: 'INSTINCT', tags: ['deception', 'defense', 'learning'] },
  { id: 'flee_first', domain: 'INSTINCT', tags: ['prey', 'survival', 'cautious'] },
  { id: 'fight_first', domain: 'INSTINCT', tags: ['predator', 'aggression', 'brave'] },
  { id: 'freeze_response', domain: 'INSTINCT', tags: ['prey', 'camouflage', 'fear'] },
  { id: 'mate_for_life', domain: 'INSTINCT', tags: ['monogamy', 'bonding', 'loyalty'] },
  { id: 'spawn_and_die', domain: 'INSTINCT', tags: ['reproduction', 'semelparous', 'mass'] },
  { id: 'guard_young', domain: 'INSTINCT', tags: ['parental', 'aggression', 'protection'] },
  { id: 'scavenging', domain: 'INSTINCT', tags: ['opportunistic', 'feeding', 'survival'] },
  { id: 'herd_following', domain: 'INSTINCT', tags: ['social', 'prey', 'safety'] },
  { id: 'dominance_seeking', domain: 'INSTINCT', tags: ['hierarchy', 'aggression', 'social'] },
  { id: 'submission_display', domain: 'INSTINCT', tags: ['social', 'hierarchy', 'peace'] },
  { id: 'tool_using', domain: 'INSTINCT', tags: ['intelligence', 'problem_solving', 'rare'] },
  { id: 'burrowing', domain: 'INSTINCT', tags: ['shelter', 'escape', 'underground'] },
  { id: 'web_building', domain: 'INSTINCT', tags: ['construction', 'hunting', 'patient'] },
  { id: 'dam_building', domain: 'INSTINCT', tags: ['construction', 'engineering', 'territory'] },
  { id: 'food_caching', domain: 'INSTINCT', tags: ['preparation', 'memory', 'winter'] },
  { id: 'alarm_calling', domain: 'INSTINCT', tags: ['social', 'warning', 'altruism'] },
  { id: 'mobbing', domain: 'INSTINCT', tags: ['social', 'defense', 'cooperation'] },
  { id: 'sunning', domain: 'INSTINCT', tags: ['thermoregulation', 'reptile', 'rest'] },
  { id: 'dust_bathing', domain: 'INSTINCT', tags: ['hygiene', 'parasite', 'comfort'] },
  { id: 'preening', domain: 'INSTINCT', tags: ['hygiene', 'feather', 'social'] },
  { id: 'stomping', domain: 'INSTINCT', tags: ['communication', 'territory', 'warning'] },
  { id: 'howling', domain: 'INSTINCT', tags: ['communication', 'pack', 'territory'] },
  { id: 'trading_instinct', domain: 'INSTINCT', tags: ['social', 'exchange', 'cooperation'] },
  { id: 'ritual_combat', domain: 'INSTINCT', tags: ['display', 'hierarchy', 'non_lethal'] },
  { id: 'gift_giving', domain: 'INSTINCT', tags: ['courtship', 'social', 'bonding'] },
  { id: 'pathfinding', domain: 'INSTINCT', tags: ['navigation', 'return', 'memory'] },
  { id: 'seasonal_mood', domain: 'INSTINCT', tags: ['cyclical', 'mating', 'aggression'] },
  { id: 'symbiosis_seeking', domain: 'INSTINCT', tags: ['cooperation', 'mutual', 'benefit'] },
  { id: 'cleaning_service', domain: 'INSTINCT', tags: ['symbiosis', 'feeding', 'mutual'] },
  { id: 'sentinel_duty', domain: 'INSTINCT', tags: ['social', 'vigilance', 'rotation'] },
  { id: 'death_feigning', domain: 'INSTINCT', tags: ['defense', 'deception', 'prey'] },

  // --- PERSONALITY_TRAIT (~40) ---
  { id: 'greed', domain: 'PERSONALITY_TRAIT', tags: ['wealth', 'accumulation', 'selfish'] },
  { id: 'honesty', domain: 'PERSONALITY_TRAIT', tags: ['truth', 'trust', 'moral'] },
  { id: 'courage', domain: 'PERSONALITY_TRAIT', tags: ['bravery', 'risk', 'action'] },
  { id: 'empathy', domain: 'PERSONALITY_TRAIT', tags: ['compassion', 'understanding', 'social'] },
  { id: 'ambition', domain: 'PERSONALITY_TRAIT', tags: ['drive', 'status', 'achievement'] },
  { id: 'curiosity', domain: 'PERSONALITY_TRAIT', tags: ['learning', 'exploration', 'open'] },
  { id: 'temper', domain: 'PERSONALITY_TRAIT', tags: ['anger', 'impulsive', 'volatile'] },
  { id: 'loyalty', domain: 'PERSONALITY_TRAIT', tags: ['faithful', 'commitment', 'group'] },
  { id: 'piety', domain: 'PERSONALITY_TRAIT', tags: ['religious', 'devotion', 'tradition'] },
  { id: 'cunning', domain: 'PERSONALITY_TRAIT', tags: ['deception', 'strategy', 'clever'] },
  { id: 'patience', domain: 'PERSONALITY_TRAIT', tags: ['waiting', 'endurance', 'calm'] },
  { id: 'vanity', domain: 'PERSONALITY_TRAIT', tags: ['appearance', 'pride', 'image'] },
  { id: 'pride', domain: 'PERSONALITY_TRAIT', tags: ['dignity', 'honor', 'stubborn'] },
  { id: 'humor', domain: 'PERSONALITY_TRAIT', tags: ['wit', 'social', 'lightness'] },
  { id: 'suspicion', domain: 'PERSONALITY_TRAIT', tags: ['distrust', 'caution', 'paranoia'] },
  { id: 'generosity', domain: 'PERSONALITY_TRAIT', tags: ['giving', 'sharing', 'altruism'] },
  { id: 'stubbornness', domain: 'PERSONALITY_TRAIT', tags: ['resistance', 'determination', 'inflexible'] },
  { id: 'kindness', domain: 'PERSONALITY_TRAIT', tags: ['gentle', 'helping', 'warmth'] },
  { id: 'cruelty', domain: 'PERSONALITY_TRAIT', tags: ['sadism', 'domination', 'cold'] },
  { id: 'cowardice', domain: 'PERSONALITY_TRAIT', tags: ['fear', 'avoidance', 'self_preservation'] },
  { id: 'diligence', domain: 'PERSONALITY_TRAIT', tags: ['work_ethic', 'thorough', 'persistent'] },
  { id: 'laziness', domain: 'PERSONALITY_TRAIT', tags: ['sloth', 'comfort', 'avoidance'] },
  { id: 'optimism', domain: 'PERSONALITY_TRAIT', tags: ['hope', 'positive', 'resilient'] },
  { id: 'pessimism', domain: 'PERSONALITY_TRAIT', tags: ['dread', 'negative', 'cautious'] },
  { id: 'charisma', domain: 'PERSONALITY_TRAIT', tags: ['influence', 'charm', 'leadership'] },
  { id: 'humility', domain: 'PERSONALITY_TRAIT', tags: ['modesty', 'selfless', 'grounded'] },
  { id: 'arrogance', domain: 'PERSONALITY_TRAIT', tags: ['superiority', 'dismissal', 'pride'] },
  { id: 'jealousy', domain: 'PERSONALITY_TRAIT', tags: ['envy', 'resentment', 'comparison'] },
  { id: 'gratitude', domain: 'PERSONALITY_TRAIT', tags: ['appreciation', 'reciprocity', 'warmth'] },
  { id: 'resentment', domain: 'PERSONALITY_TRAIT', tags: ['grudge', 'bitterness', 'memory'] },
  { id: 'adaptability', domain: 'PERSONALITY_TRAIT', tags: ['flexibility', 'change', 'resilience'] },
  { id: 'traditionalism', domain: 'PERSONALITY_TRAIT', tags: ['conservative', 'custom', 'resistance'] },
  { id: 'creativity', domain: 'PERSONALITY_TRAIT', tags: ['innovation', 'art', 'novelty'] },
  { id: 'discipline', domain: 'PERSONALITY_TRAIT', tags: ['control', 'routine', 'focus'] },
  { id: 'impulsiveness', domain: 'PERSONALITY_TRAIT', tags: ['rash', 'spontaneous', 'risk'] },
  { id: 'nurturing', domain: 'PERSONALITY_TRAIT', tags: ['caring', 'parental', 'protective'] },
  { id: 'competitiveness', domain: 'PERSONALITY_TRAIT', tags: ['rivalry', 'winning', 'drive'] },
  { id: 'cooperativeness', domain: 'PERSONALITY_TRAIT', tags: ['teamwork', 'sharing', 'harmony'] },
  { id: 'vengefulness', domain: 'PERSONALITY_TRAIT', tags: ['revenge', 'grudge', 'justice'] },
  { id: 'forgiveness', domain: 'PERSONALITY_TRAIT', tags: ['mercy', 'letting_go', 'peace'] },

  // --- SKILL (~40) ---
  { id: 'farming', domain: 'SKILL', tags: ['food', 'land', 'seasonal'] },
  { id: 'trading', domain: 'SKILL', tags: ['commerce', 'negotiation', 'value'] },
  { id: 'crafting', domain: 'SKILL', tags: ['creation', 'tools', 'quality'] },
  { id: 'fighting', domain: 'SKILL', tags: ['combat', 'weapons', 'strength'] },
  { id: 'stealth', domain: 'SKILL', tags: ['sneaking', 'hiding', 'undetected'] },
  { id: 'persuasion', domain: 'SKILL', tags: ['speech', 'influence', 'diplomacy'] },
  { id: 'medicine', domain: 'SKILL', tags: ['healing', 'herbs', 'knowledge'] },
  { id: 'scholarship', domain: 'SKILL', tags: ['learning', 'books', 'theory'] },
  { id: 'leadership', domain: 'SKILL', tags: ['command', 'inspiration', 'strategy'] },
  { id: 'lockpicking', domain: 'SKILL', tags: ['entry', 'finesse', 'crime'] },
  { id: 'forgery', domain: 'SKILL', tags: ['deception', 'craft', 'documents'] },
  { id: 'navigation', domain: 'SKILL', tags: ['direction', 'maps', 'sea'] },
  { id: 'cooking', domain: 'SKILL', tags: ['food', 'flavor', 'preparation'] },
  { id: 'smithing', domain: 'SKILL', tags: ['metal', 'forge', 'weapons'] },
  { id: 'tailoring', domain: 'SKILL', tags: ['cloth', 'fashion', 'repair'] },
  { id: 'brewing', domain: 'SKILL', tags: ['drink', 'fermentation', 'trade'] },
  { id: 'hunting', domain: 'SKILL', tags: ['tracking', 'weapons', 'wilderness'] },
  { id: 'fishing', domain: 'SKILL', tags: ['water', 'patience', 'food'] },
  { id: 'riding', domain: 'SKILL', tags: ['animal', 'transport', 'speed'] },
  { id: 'singing', domain: 'SKILL', tags: ['performance', 'culture', 'morale'] },
  { id: 'dancing', domain: 'SKILL', tags: ['performance', 'grace', 'social'] },
  { id: 'storytelling', domain: 'SKILL', tags: ['entertainment', 'culture', 'memory'] },
  { id: 'carpentry', domain: 'SKILL', tags: ['wood', 'building', 'repair'] },
  { id: 'masonry', domain: 'SKILL', tags: ['stone', 'building', 'durability'] },
  { id: 'herbalism', domain: 'SKILL', tags: ['plants', 'medicine', 'knowledge'] },
  { id: 'mining', domain: 'SKILL', tags: ['extraction', 'ore', 'danger'] },
  { id: 'logging', domain: 'SKILL', tags: ['wood', 'labor', 'danger'] },
  { id: 'accounting', domain: 'SKILL', tags: ['numbers', 'records', 'commerce'] },
  { id: 'diplomacy', domain: 'SKILL', tags: ['negotiation', 'peace', 'alliance'] },
  { id: 'intimidation', domain: 'SKILL', tags: ['fear', 'force', 'dominance'] },
  { id: 'acrobatics', domain: 'SKILL', tags: ['agility', 'performance', 'escape'] },
  { id: 'archery', domain: 'SKILL', tags: ['ranged', 'precision', 'hunting'] },
  { id: 'swimming', domain: 'SKILL', tags: ['water', 'survival', 'transport'] },
  { id: 'first_aid', domain: 'SKILL', tags: ['emergency', 'bandaging', 'stabilize'] },
  { id: 'survival', domain: 'SKILL', tags: ['wilderness', 'shelter', 'foraging'] },
  { id: 'animal_handling', domain: 'SKILL', tags: ['training', 'beasts', 'care'] },
  { id: 'cartography', domain: 'SKILL', tags: ['mapping', 'exploration', 'knowledge'] },
  { id: 'engineering', domain: 'SKILL', tags: ['design', 'structures', 'mechanisms'] },
  { id: 'rhetoric', domain: 'SKILL', tags: ['speech', 'debate', 'influence'] },
  { id: 'espionage', domain: 'SKILL', tags: ['secrets', 'disguise', 'intelligence'] },

  // --- MATERIAL (~50) ---
  { id: 'iron', domain: 'MATERIAL', tags: ['metal', 'common', 'tools'] },
  { id: 'bronze', domain: 'MATERIAL', tags: ['metal', 'alloy', 'decorative'] },
  { id: 'steel', domain: 'MATERIAL', tags: ['metal', 'strong', 'weapons'] },
  { id: 'wood_oak', domain: 'MATERIAL', tags: ['wood', 'hard', 'building'] },
  { id: 'wood_pine', domain: 'MATERIAL', tags: ['wood', 'soft', 'fuel'] },
  { id: 'stone_granite', domain: 'MATERIAL', tags: ['stone', 'hard', 'building'] },
  { id: 'clay', domain: 'MATERIAL', tags: ['earth', 'pottery', 'brick'] },
  { id: 'cloth_wool', domain: 'MATERIAL', tags: ['textile', 'warm', 'common'] },
  { id: 'cloth_linen', domain: 'MATERIAL', tags: ['textile', 'light', 'summer'] },
  { id: 'leather', domain: 'MATERIAL', tags: ['animal', 'durable', 'armor'] },
  { id: 'glass', domain: 'MATERIAL', tags: ['fragile', 'transparent', 'luxury'] },
  { id: 'salt', domain: 'MATERIAL', tags: ['preservative', 'seasoning', 'trade'] },
  { id: 'grain_wheat', domain: 'MATERIAL', tags: ['food', 'staple', 'grain'] },
  { id: 'grain_barley', domain: 'MATERIAL', tags: ['food', 'brewing', 'grain'] },
  { id: 'fruit', domain: 'MATERIAL', tags: ['food', 'fresh', 'seasonal'] },
  { id: 'meat', domain: 'MATERIAL', tags: ['food', 'protein', 'perishable'] },
  { id: 'fish', domain: 'MATERIAL', tags: ['food', 'aquatic', 'perishable'] },
  { id: 'honey', domain: 'MATERIAL', tags: ['food', 'sweet', 'medicine'] },
  { id: 'herbs', domain: 'MATERIAL', tags: ['medicine', 'cooking', 'natural'] },
  { id: 'coal', domain: 'MATERIAL', tags: ['fuel', 'forge', 'mining'] },
  { id: 'gold', domain: 'MATERIAL', tags: ['precious', 'currency', 'decorative'] },
  { id: 'silver', domain: 'MATERIAL', tags: ['precious', 'currency', 'ornamental'] },
  { id: 'copper', domain: 'MATERIAL', tags: ['metal', 'conductive', 'alloy'] },
  { id: 'tin', domain: 'MATERIAL', tags: ['metal', 'alloy', 'coating'] },
  { id: 'rope', domain: 'MATERIAL', tags: ['binding', 'construction', 'tool'] },
  { id: 'tar', domain: 'MATERIAL', tags: ['waterproof', 'fuel', 'adhesive'] },
  { id: 'pitch', domain: 'MATERIAL', tags: ['adhesive', 'waterproof', 'building'] },
  { id: 'lime', domain: 'MATERIAL', tags: ['building', 'mortar', 'agriculture'] },
  { id: 'sand', domain: 'MATERIAL', tags: ['building', 'glass', 'mortar'] },
  { id: 'straw', domain: 'MATERIAL', tags: ['bedding', 'thatching', 'feed'] },
  { id: 'feather', domain: 'MATERIAL', tags: ['bedding', 'writing', 'light'] },
  { id: 'bone', domain: 'MATERIAL', tags: ['tool', 'decorative', 'craft'] },
  { id: 'ivory', domain: 'MATERIAL', tags: ['luxury', 'carving', 'rare'] },
  { id: 'pearl', domain: 'MATERIAL', tags: ['luxury', 'jewelry', 'aquatic'] },
  { id: 'gem_ruby', domain: 'MATERIAL', tags: ['luxury', 'jewelry', 'red'] },
  { id: 'gem_sapphire', domain: 'MATERIAL', tags: ['luxury', 'jewelry', 'blue'] },
  { id: 'gem_emerald', domain: 'MATERIAL', tags: ['luxury', 'jewelry', 'green'] },
  { id: 'silk', domain: 'MATERIAL', tags: ['luxury', 'textile', 'import'] },
  { id: 'spice', domain: 'MATERIAL', tags: ['luxury', 'cooking', 'import'] },
  { id: 'wine', domain: 'MATERIAL', tags: ['luxury', 'drink', 'trade'] },
  { id: 'oil', domain: 'MATERIAL', tags: ['fuel', 'cooking', 'lamp'] },
  { id: 'wax', domain: 'MATERIAL', tags: ['light', 'sealing', 'craft'] },
  { id: 'paper', domain: 'MATERIAL', tags: ['writing', 'records', 'fragile'] },
  { id: 'ink', domain: 'MATERIAL', tags: ['writing', 'records', 'trade'] },
  { id: 'dye', domain: 'MATERIAL', tags: ['color', 'textile', 'luxury'] },
  { id: 'resin', domain: 'MATERIAL', tags: ['adhesive', 'incense', 'preservative'] },
  { id: 'fur', domain: 'MATERIAL', tags: ['luxury', 'warmth', 'trade'] },
  { id: 'tobacco', domain: 'MATERIAL', tags: ['luxury', 'addictive', 'trade'] },
  { id: 'opium', domain: 'MATERIAL', tags: ['contraband', 'addictive', 'medicine'] },
  { id: 'gunpowder', domain: 'MATERIAL', tags: ['explosive', 'weapon', 'rare'] },

  // --- ENVIRONMENT_ADAPTATION (~35) ---
  { id: 'cold_resistant', domain: 'ENVIRONMENT_ADAPTATION', tags: ['arctic', 'winter', 'fur'] },
  { id: 'heat_resistant', domain: 'ENVIRONMENT_ADAPTATION', tags: ['desert', 'summer', 'endurance'] },
  { id: 'aquatic', domain: 'ENVIRONMENT_ADAPTATION', tags: ['water', 'swimming', 'gills'] },
  { id: 'arboreal', domain: 'ENVIRONMENT_ADAPTATION', tags: ['forest', 'climbing', 'branches'] },
  { id: 'burrowing', domain: 'ENVIRONMENT_ADAPTATION', tags: ['underground', 'tunnel', 'hiding'] },
  { id: 'desert_adapted', domain: 'ENVIRONMENT_ADAPTATION', tags: ['arid', 'water_conserve', 'nocturnal'] },
  { id: 'forest_camouflage', domain: 'ENVIRONMENT_ADAPTATION', tags: ['green', 'stealth', 'ambush'] },
  { id: 'swamp_adapted', domain: 'ENVIRONMENT_ADAPTATION', tags: ['wet', 'mud', 'amphibious'] },
  { id: 'altitude_tolerant', domain: 'ENVIRONMENT_ADAPTATION', tags: ['mountain', 'thin_air', 'cold'] },
  { id: 'cave_dwelling', domain: 'ENVIRONMENT_ADAPTATION', tags: ['dark', 'echo', 'stable_temp'] },
  { id: 'coastal', domain: 'ENVIRONMENT_ADAPTATION', tags: ['salt', 'tide', 'wind'] },
  { id: 'grassland', domain: 'ENVIRONMENT_ADAPTATION', tags: ['open', 'running', 'herd'] },
  { id: 'tundra', domain: 'ENVIRONMENT_ADAPTATION', tags: ['frozen', 'sparse', 'migration'] },
  { id: 'rainforest', domain: 'ENVIRONMENT_ADAPTATION', tags: ['humid', 'dense', 'layered'] },
  { id: 'volcanic', domain: 'ENVIRONMENT_ADAPTATION', tags: ['heat', 'sulfur', 'mineral'] },
  { id: 'urban', domain: 'ENVIRONMENT_ADAPTATION', tags: ['adapted', 'scavenging', 'noise'] },
  { id: 'nocturnal_habitat', domain: 'ENVIRONMENT_ADAPTATION', tags: ['dark', 'quiet', 'hunting'] },
  { id: 'freshwater', domain: 'ENVIRONMENT_ADAPTATION', tags: ['river', 'lake', 'clean'] },
  { id: 'saltwater', domain: 'ENVIRONMENT_ADAPTATION', tags: ['ocean', 'deep', 'pressure'] },
  { id: 'mangrove', domain: 'ENVIRONMENT_ADAPTATION', tags: ['brackish', 'root', 'tidal'] },
  { id: 'savanna', domain: 'ENVIRONMENT_ADAPTATION', tags: ['seasonal', 'open', 'herd'] },
  { id: 'alpine', domain: 'ENVIRONMENT_ADAPTATION', tags: ['high', 'cold', 'sparse'] },
  { id: 'subterranean', domain: 'ENVIRONMENT_ADAPTATION', tags: ['deep', 'dark', 'pressure'] },
  { id: 'polar', domain: 'ENVIRONMENT_ADAPTATION', tags: ['ice', 'extreme_cold', 'white'] },
  { id: 'tropical', domain: 'ENVIRONMENT_ADAPTATION', tags: ['hot', 'humid', 'diverse'] },
  { id: 'temperate', domain: 'ENVIRONMENT_ADAPTATION', tags: ['moderate', 'seasonal', 'balanced'] },
  { id: 'riverine', domain: 'ENVIRONMENT_ADAPTATION', tags: ['flowing', 'freshwater', 'fertile'] },
  { id: 'island', domain: 'ENVIRONMENT_ADAPTATION', tags: ['isolated', 'endemic', 'limited'] },
  { id: 'wetland', domain: 'ENVIRONMENT_ADAPTATION', tags: ['marsh', 'waterlogged', 'rich'] },
  { id: 'cliff_dwelling', domain: 'ENVIRONMENT_ADAPTATION', tags: ['vertical', 'nesting', 'aerial'] },
  { id: 'coral_reef', domain: 'ENVIRONMENT_ADAPTATION', tags: ['shallow', 'diverse', 'symbiotic'] },
  { id: 'deep_ocean', domain: 'ENVIRONMENT_ADAPTATION', tags: ['pressure', 'dark', 'bioluminescent'] },
  { id: 'floodplain', domain: 'ENVIRONMENT_ADAPTATION', tags: ['seasonal_flood', 'fertile', 'mud'] },
  { id: 'steppe', domain: 'ENVIRONMENT_ADAPTATION', tags: ['dry', 'windy', 'grass'] },
  { id: 'monsoon', domain: 'ENVIRONMENT_ADAPTATION', tags: ['seasonal_rain', 'lush', 'cyclical'] },

  // --- SOCIAL_STRUCTURE (~40) ---
  { id: 'family_clan', domain: 'SOCIAL_STRUCTURE', tags: ['kinship', 'loyalty', 'hereditary'] },
  { id: 'guild_member', domain: 'SOCIAL_STRUCTURE', tags: ['profession', 'training', 'monopoly'] },
  { id: 'hierarchy_rigid', domain: 'SOCIAL_STRUCTURE', tags: ['class', 'obedience', 'status'] },
  { id: 'matriarchy', domain: 'SOCIAL_STRUCTURE', tags: ['female_lead', 'lineage', 'inheritance'] },
  { id: 'tribute_system', domain: 'SOCIAL_STRUCTURE', tags: ['tax', 'subjugation', 'exchange'] },
  { id: 'oath_bound', domain: 'SOCIAL_STRUCTURE', tags: ['promise', 'honor', 'binding'] },
  { id: 'exile', domain: 'SOCIAL_STRUCTURE', tags: ['banishment', 'outcast', 'shame'] },
  { id: 'outcast', domain: 'SOCIAL_STRUCTURE', tags: ['rejected', 'alone', 'stigma'] },
  { id: 'alliance', domain: 'SOCIAL_STRUCTURE', tags: ['pact', 'mutual', 'defense'] },
  { id: 'blood_feud', domain: 'SOCIAL_STRUCTURE', tags: ['vendetta', 'honor', 'generational'] },
  { id: 'democracy', domain: 'SOCIAL_STRUCTURE', tags: ['vote', 'equality', 'debate'] },
  { id: 'monarchy', domain: 'SOCIAL_STRUCTURE', tags: ['ruler', 'hereditary', 'crown'] },
  { id: 'oligarchy', domain: 'SOCIAL_STRUCTURE', tags: ['elite', 'wealth', 'control'] },
  { id: 'theocracy', domain: 'SOCIAL_STRUCTURE', tags: ['religious', 'divine', 'law'] },
  { id: 'meritocracy', domain: 'SOCIAL_STRUCTURE', tags: ['skill', 'achievement', 'fair'] },
  { id: 'slavery', domain: 'SOCIAL_STRUCTURE', tags: ['ownership', 'forced', 'unfree'] },
  { id: 'feudalism', domain: 'SOCIAL_STRUCTURE', tags: ['land', 'service', 'lord'] },
  { id: 'nomadic', domain: 'SOCIAL_STRUCTURE', tags: ['mobile', 'tribe', 'herding'] },
  { id: 'settled', domain: 'SOCIAL_STRUCTURE', tags: ['permanent', 'agriculture', 'property'] },
  { id: 'secret_society', domain: 'SOCIAL_STRUCTURE', tags: ['hidden', 'initiation', 'knowledge'] },
  { id: 'criminal_underground', domain: 'SOCIAL_STRUCTURE', tags: ['illegal', 'network', 'shadow'] },
  { id: 'merchant_guild', domain: 'SOCIAL_STRUCTURE', tags: ['trade', 'monopoly', 'wealth'] },
  { id: 'military_order', domain: 'SOCIAL_STRUCTURE', tags: ['warrior', 'discipline', 'honor'] },
  { id: 'religious_order', domain: 'SOCIAL_STRUCTURE', tags: ['faith', 'service', 'celibacy'] },
  { id: 'artisan_collective', domain: 'SOCIAL_STRUCTURE', tags: ['craft', 'shared', 'quality'] },
  { id: 'farmer_collective', domain: 'SOCIAL_STRUCTURE', tags: ['agriculture', 'shared', 'cooperation'] },
  { id: 'guard_faction', domain: 'SOCIAL_STRUCTURE', tags: ['law', 'protection', 'authority'] },
  { id: 'council', domain: 'SOCIAL_STRUCTURE', tags: ['governance', 'debate', 'decision'] },
  { id: 'patronage', domain: 'SOCIAL_STRUCTURE', tags: ['sponsorship', 'debt', 'influence'] },
  { id: 'apprenticeship', domain: 'SOCIAL_STRUCTURE', tags: ['training', 'master', 'learning'] },
  { id: 'debt_bondage', domain: 'SOCIAL_STRUCTURE', tags: ['obligation', 'work', 'unfree'] },
  { id: 'foster_child', domain: 'SOCIAL_STRUCTURE', tags: ['raising', 'non_blood', 'bond'] },
  { id: 'adoption', domain: 'SOCIAL_STRUCTURE', tags: ['family', 'legal', 'care'] },
  { id: 'marriage_alliance', domain: 'SOCIAL_STRUCTURE', tags: ['political', 'union', 'strategic'] },
  { id: 'blood_oath', domain: 'SOCIAL_STRUCTURE', tags: ['binding', 'sacred', 'eternal'] },
  { id: 'rivalry', domain: 'SOCIAL_STRUCTURE', tags: ['competition', 'tension', 'personal'] },
  { id: 'mentorship', domain: 'SOCIAL_STRUCTURE', tags: ['teaching', 'guidance', 'growth'] },
  { id: 'debt_network', domain: 'SOCIAL_STRUCTURE', tags: ['obligation', 'finance', 'interconnected'] },
  { id: 'neighborhood', domain: 'SOCIAL_STRUCTURE', tags: ['proximity', 'community', 'local'] },
  { id: 'black_market', domain: 'SOCIAL_STRUCTURE', tags: ['illegal', 'trade', 'hidden'] },

  // --- ITEM_TYPE (~50) ---
  { id: 'sword', domain: 'ITEM_TYPE', tags: ['weapon', 'melee', 'metal'] },
  { id: 'dagger', domain: 'ITEM_TYPE', tags: ['weapon', 'melee', 'concealable'] },
  { id: 'bow', domain: 'ITEM_TYPE', tags: ['weapon', 'ranged', 'wood'] },
  { id: 'spear', domain: 'ITEM_TYPE', tags: ['weapon', 'melee', 'reach'] },
  { id: 'shield', domain: 'ITEM_TYPE', tags: ['defense', 'blocking', 'wood'] },
  { id: 'armor_light', domain: 'ITEM_TYPE', tags: ['defense', 'mobile', 'leather'] },
  { id: 'armor_heavy', domain: 'ITEM_TYPE', tags: ['defense', 'slow', 'metal'] },
  { id: 'tool_plow', domain: 'ITEM_TYPE', tags: ['farming', 'soil', 'iron'] },
  { id: 'tool_hammer', domain: 'ITEM_TYPE', tags: ['crafting', 'building', 'metal'] },
  { id: 'lockpick', domain: 'ITEM_TYPE', tags: ['crime', 'entry', 'finesse'] },
  { id: 'torch', domain: 'ITEM_TYPE', tags: ['light', 'fire', 'disposable'] },
  { id: 'lantern', domain: 'ITEM_TYPE', tags: ['light', 'reusable', 'oil'] },
  { id: 'rope', domain: 'ITEM_TYPE', tags: ['utility', 'binding', 'climbing'] },
  { id: 'medicine_herb', domain: 'ITEM_TYPE', tags: ['healing', 'consumable', 'natural'] },
  { id: 'poison_vial', domain: 'ITEM_TYPE', tags: ['weapon', 'consumable', 'crime'] },
  { id: 'contraband', domain: 'ITEM_TYPE', tags: ['illegal', 'trade', 'hidden'] },
  { id: 'ledger', domain: 'ITEM_TYPE', tags: ['records', 'commerce', 'evidence'] },
  { id: 'deed', domain: 'ITEM_TYPE', tags: ['property', 'legal', 'ownership'] },
  { id: 'letter', domain: 'ITEM_TYPE', tags: ['communication', 'secrets', 'paper'] },
  { id: 'key', domain: 'ITEM_TYPE', tags: ['access', 'security', 'metal'] },
  { id: 'map', domain: 'ITEM_TYPE', tags: ['navigation', 'exploration', 'paper'] },
  { id: 'compass', domain: 'ITEM_TYPE', tags: ['navigation', 'direction', 'metal'] },
  { id: 'spyglass', domain: 'ITEM_TYPE', tags: ['observation', 'distance', 'glass'] },
  { id: 'chalice', domain: 'ITEM_TYPE', tags: ['religious', 'luxury', 'metal'] },
  { id: 'crown', domain: 'ITEM_TYPE', tags: ['authority', 'luxury', 'symbol'] },
  { id: 'seal_ring', domain: 'ITEM_TYPE', tags: ['authority', 'signet', 'metal'] },
  { id: 'chain', domain: 'ITEM_TYPE', tags: ['binding', 'metal', 'restraint'] },
  { id: 'manacles', domain: 'ITEM_TYPE', tags: ['restraint', 'law', 'metal'] },
  { id: 'whip', domain: 'ITEM_TYPE', tags: ['weapon', 'punishment', 'leather'] },
  { id: 'net', domain: 'ITEM_TYPE', tags: ['fishing', 'trapping', 'rope'] },
  { id: 'axe', domain: 'ITEM_TYPE', tags: ['weapon', 'tool', 'wood'] },
  { id: 'saw', domain: 'ITEM_TYPE', tags: ['tool', 'wood', 'cutting'] },
  { id: 'needle', domain: 'ITEM_TYPE', tags: ['tool', 'tailoring', 'fine'] },
  { id: 'cauldron', domain: 'ITEM_TYPE', tags: ['cooking', 'brewing', 'metal'] },
  { id: 'barrel', domain: 'ITEM_TYPE', tags: ['storage', 'liquid', 'wood'] },
  { id: 'cart', domain: 'ITEM_TYPE', tags: ['transport', 'wood', 'trade'] },
  { id: 'boat_small', domain: 'ITEM_TYPE', tags: ['transport', 'water', 'wood'] },
  { id: 'tent', domain: 'ITEM_TYPE', tags: ['shelter', 'portable', 'cloth'] },
  { id: 'bed', domain: 'ITEM_TYPE', tags: ['rest', 'furniture', 'comfort'] },
  { id: 'book', domain: 'ITEM_TYPE', tags: ['knowledge', 'scholarship', 'paper'] },
  { id: 'scroll', domain: 'ITEM_TYPE', tags: ['knowledge', 'magic', 'paper'] },
  { id: 'musical_instrument', domain: 'ITEM_TYPE', tags: ['entertainment', 'culture', 'wood'] },
  { id: 'gambling_dice', domain: 'ITEM_TYPE', tags: ['game', 'chance', 'bone'] },
  { id: 'mirror', domain: 'ITEM_TYPE', tags: ['vanity', 'glass', 'luxury'] },
  { id: 'perfume', domain: 'ITEM_TYPE', tags: ['luxury', 'scent', 'social'] },
  { id: 'jewelry', domain: 'ITEM_TYPE', tags: ['luxury', 'status', 'metal'] },
  { id: 'banner', domain: 'ITEM_TYPE', tags: ['symbol', 'faction', 'cloth'] },
  { id: 'coffin', domain: 'ITEM_TYPE', tags: ['death', 'ritual', 'wood'] },
  { id: 'idol', domain: 'ITEM_TYPE', tags: ['religious', 'symbol', 'stone'] },
  { id: 'treasure_chest', domain: 'ITEM_TYPE', tags: ['storage', 'valuables', 'wood'] },
];

// ============================================================
// SECTION 2: TEXT TEMPLATES (4+ variants per action/event)
// ============================================================

export const TEMPLATES: Record<string, string[]> = {
  work: [
    '{npc} spent the day working as {job} in the {district}.',
    'Another day of toil for {npc}, laboring at {job} in {district}.',
    '{npc} put in honest hours at {job}, earning a few coins.',
    'The {district} district saw {npc} working steadily at {job}.',
    '{npc} toiled away at {job}, the routine familiar and grounding.',
  ],
  trade: [
    '{npc} brokered a deal in the market, trading {goods}.',
    'A shrewd trade was made by {npc}: {goods} changed hands.',
    '{npc} navigated the market with {goods}, finding a willing partner.',
    'Commerce flowed as {npc} traded {goods} for a fair price.',
    'In the bustling market, {npc} completed a trade of {goods}.',
  ],
  buy: [
    '{npc} purchased {goods} from a merchant.',
    'Coins changed hands as {npc} bought {goods}.',
    '{npc} acquired {goods} at the market today.',
    'A purchase was made: {npc} now owns {goods}.',
    '{npc} spent coin to obtain {goods} from a seller.',
  ],
  sell: [
    '{npc} sold {goods} at a good price.',
    'Merchant {npc} found a buyer for {goods}.',
    '{npc} parted with {goods} for a handful of coin.',
    'The sale of {goods} by {npc} was completed smoothly.',
    '{npc} turned {goods} into coin at the market.',
  ],
  eat: [
    '{npc} sat down to a meal, hunger sated.',
    'Food found its way to {npc}\'s table tonight.',
    '{npc} ate well today, strength restored.',
    'A warm meal comforted {npc} after a long day.',
    '{npc} broke bread and ate, feeling renewed.',
  ],
  sleep: [
    '{npc} retired for the night, seeking rest.',
    'Sleep claimed {npc} as darkness fell.',
    '{npc} found their bed and drifted off.',
    'Exhaustion took {npc}, who slept deeply.',
    '{npc} closed their eyes, the day done.',
  ],
  socialize: [
    '{npc} spent time with {target}, sharing stories.',
    'Conversation flowed between {npc} and {target}.',
    '{npc} and {target} enjoyed each other\'s company.',
    'Laughter was heard as {npc} socialized with {target}.',
    '{npc} sought out {target} for friendly company.',
  ],
  gossip: [
    '{npc} spread rumors about {target} to anyone who\'d listen.',
    'Whispers traveled from {npc}\'s lips: tales of {target}.',
    '{npc} couldn\'t resist sharing gossip about {target}.',
    'In hushed tones, {npc} gossiped about {target}.',
    '{npc} planted seeds of rumor regarding {target}.',
  ],
  court: [
    '{npc} courted {target} with flowers and kind words.',
    'Romance bloomed as {npc} pursued {target}\'s affection.',
    '{npc} wooed {target}, hope evident in every gesture.',
    'The dance of courtship: {npc} charmed {target}.',
    '{npc} made their interest in {target} known.',
  ],
  marry: [
    '{npc} and {target} were joined in marriage!',
    'A wedding was celebrated: {npc} wed {target}.',
    'Before witnesses, {npc} and {target} pledged their lives together.',
    'Love triumphed as {npc} married {target}.',
    'The settlement rejoiced as {npc} and {target} became one.',
  ],
  argue: [
    'Heated words flew between {npc} and {target}.',
    '{npc} and {target} argued bitterly, voices raised.',
    'A dispute erupted: {npc} clashed with {target}.',
    '{npc} and {target} could not see eye to eye, anger flaring.',
    'Tension broke as {npc} argued fiercely with {target}.',
  ],
  fight: [
    '{npc} and {target} came to blows!',
    'Violence erupted between {npc} and {target}.',
    'Fists flew as {npc} fought {target}.',
    '{npc} attacked {target} in a brutal confrontation.',
    'Blood was shed as {npc} and {target} brawled.',
  ],
  steal: [
    '{npc} stole from {target} under cover of darkness.',
    'A theft! {npc} took {goods} from {target}.',
    '{target} was robbed by {npc}, who slipped away unseen.',
    '{npc}\'s fingers were quick, taking from {target}.',
    'In a moment of desperation, {npc} stole from {target}.',
  ],
  pickpocket: [
    '{npc} deftly lifted coin from {target}\'s purse.',
    'A deft hand: {npc} pickpocketed {target}.',
    '{target} never noticed {npc}\'s thieving fingers.',
    '{npc} relieved {target} of coin without a sound.',
    'Skill and nerve: {npc} picked {target}\'s pocket.',
  ],
  burgle: [
    '{npc} broke into {target}\'s home under moonlight.',
    'A burglary! {npc} ransacked {target}\'s dwelling.',
    '{target} awoke to find {npc} had stolen their valuables.',
    '{npc} crept through {target}\'s home, taking what they could.',
    'Under cover of night, {npc} burgled {target}.',
  ],
  rob: [
    '{npc} robbed {target} at knifepoint!',
    'Violent theft: {npc} mugged {target} in the street.',
    '{target} was held up by {npc}, who took everything.',
    'Fear gripped {target} as {npc} demanded their coin.',
    '{npc} waylaid {target} and took their belongings by force.',
  ],
  smuggle: [
    '{npc} smuggled contraband through the docks.',
    'Under cover of night, {npc} moved illegal goods.',
    '{npc} slipped {goods} past the guards unseen.',
    'The smuggler {npc} moved shadowed cargo through {district}.',
    '{npc} ran contraband, avoiding the watchful eyes of guards.',
  ],
  bribe: [
    '{npc} slipped coin to {target} for a favor.',
    'Corruption: {npc} bribed {target} to look the other way.',
    '{target} accepted {npc}\'s bribe with a knowing nod.',
    '{npc} greased palms, paying {target} for silence.',
    'A quiet exchange: {npc} bribed {target} successfully.',
  ],
  blackmail: [
    '{npc} blackmailed {target} with damaging information.',
    'Threat and leverage: {npc} coerced {target}.',
    '{target} was forced to comply as {npc} held secrets over them.',
    '{npc} wielded knowledge like a weapon against {target}.',
    'The shadow of scandal: {npc} blackmailed {target}.',
  ],
  extort: [
    '{npc} extorted protection money from {target}.',
    'Fear drove {target} to pay {npc}\'s demanded tribute.',
    '{npc} squeezed {target} for coin through threats.',
    'Tribute extracted: {npc} preyed on {target}\'s fear.',
    '{target} paid up as {npc} made their threats clear.',
  ],
  lend_money: [
    '{npc} lent coin to {target}, expecting repayment.',
    'A debt was created: {npc} lent money to {target}.',
    '{target} borrowed from {npc}, promising to repay.',
    '{npc} extended credit to {target}, trust or naivety guiding the choice.',
    'Coin flowed from {npc} to {target} as a loan.',
  ],
  borrow_money: [
    '{npc} borrowed coin from {target}, desperate.',
    'In need, {npc} sought a loan from {target}.',
    '{target} agreed to lend to {npc}, who accepted the debt.',
    'Debt bound {npc} to {target} as they borrowed coin.',
    '{npc} swallowed pride and borrowed from {target}.',
  ],
  repay_debt: [
    '{npc} repaid their debt to {target}, honor satisfied.',
    'A debt settled: {npc} returned coin to {target}.',
    '{npc} honored their obligation, paying {target} in full.',
    'Trust restored as {npc} repaid {target}.',
    '{npc} cleared their debt to {target}, relieved.',
  ],
  default_on_debt: [
    '{npc} failed to repay {target}, breaking their promise.',
    'Debt unpaid: {npc} defaulted on what they owed {target}.',
    '{target} waited in vain as {npc} could not repay.',
    'Broken promise: {npc} defaulted on their debt to {target}.',
    '{npc} could not pay {target}, trust eroding.',
  ],
  forgive_debt: [
    '{npc} forgave {target}\'s debt, an act of mercy.',
    'Generosity: {npc} released {target} from their obligation.',
    '{npc} chose compassion, forgiving what {target} owed.',
    'The debt was wiped clean as {npc} forgave {target}.',
    '{npc} let go of {target}\'s debt, earning gratitude.',
  ],
  donate: [
    '{npc} donated coin to the settlement\'s common fund.',
    'Charity: {npc} gave freely to those in need.',
    '{npc} shared their wealth with the community.',
    'A generous act: {npc} donated to the public good.',
    '{npc} gave coin without expectation of return.',
  ],
  beg: [
    '{npc} begged on the streets, hat outstretched.',
    'Humility and hunger: {npc} begged for coin.',
    '{npc} appealed to passersby for charity.',
    'Pride set aside, {npc} begged for survival.',
    '{npc}\'s desperate pleas echoed through {district}.',
  ],
  share_food: [
    '{npc} shared their food with {target}.',
    'Kindness: {npc} offered food to {target}.',
    '{target} received a meal from {npc}\'s generosity.',
    '{npc} divided their bread with {target}.',
    'Compassion shown: {npc} fed {target}.',
  ],
  hoard: [
    '{npc} hoarded supplies, stockpiling against hard times.',
    'Greed or caution: {npc} accumulated resources.',
    '{npc} locked away goods, refusing to share.',
    'The stores of {npc} grew as they hoarded.',
    '{npc} gathered supplies selfishly, eyes on their own survival.',
  ],
  help: [
    '{npc} helped {target} in their time of need.',
    'A kind act: {npc} assisted {target}.',
    '{target} was aided by {npc}\'s willing hands.',
    '{npc} extended a hand to {target}, offering help.',
    'Solidarity: {npc} came to {target}\'s aid.',
  ],
  betray: [
    '{npc} betrayed {target}, shattering trust.',
    'Treachery! {npc} turned against {target}.',
    'The knife in the back: {npc} betrayed {target}.',
    '{target} never expected {npc}\'s betrayal.',
    'Loyalty died as {npc} betrayed {target}.',
  ],
  lie: [
    '{npc} lied to {target}, weaving a false tale.',
    'Deception: {npc} spoke untruths to {target}.',
    '{target} was misled by {npc}\'s smooth lies.',
    '{npc}\'s words were honey-coated poison for {target}.',
    'Falsehood flowed from {npc}\'s lips to {target}.',
  ],
  confess: [
    '{npc} confessed their wrongs to {target}.',
    'Truth at last: {npc} admitted their guilt to {target}.',
    'Burden lifted, {npc} confessed everything to {target}.',
    '{npc} unburdened their conscience before {target}.',
    'Remorse drove {npc} to confess to {target}.',
  ],
  accuse: [
    '{npc} accused {target} of a crime!',
    'An accusation rang out: {npc} pointed at {target}.',
    '{target} was accused by {npc}, shock rippling through witnesses.',
    '{npc} publicly accused {target}, demanding justice.',
    'Finger pointed: {npc} accused {target} before all.',
  ],
  investigate: [
    '{npc} investigated the matter, searching for truth.',
    'Clues gathered as {npc} pursued the investigation.',
    '{npc} dug deeper, seeking answers.',
    'The investigator {npc} followed the trail.',
    '{npc} questioned witnesses and examined evidence.',
  ],
  arrest: [
    '{npc} arrested {target} for their crimes!',
    'Justice: {npc} took {target} into custody.',
    '{target} was apprehended by {npc}, chains ready.',
    '{npc} enforced the law, arresting {target}.',
    'The long arm of the law: {npc} arrested {target}.',
  ],
  imprison: [
    '{target} was imprisoned by {npc}\'s order.',
    'Behind bars: {npc} had {target} locked away.',
    '{npc} sentenced {target} to imprisonment.',
    'The cell door closed on {target}, by {npc}\'s hand.',
    '{npc} ensured {target} would rot in a cell.',
  ],
  punish: [
    '{npc} punished {target} for their transgressions.',
    'Justice was served as {npc} punished {target}.',
    '{target} suffered punishment at {npc}\'s command.',
    '{npc} made {target} pay for their crimes.',
    'The price of wrongdoing: {npc} punished {target}.',
  ],
  pardon: [
    '{npc} pardoned {target}, showing mercy.',
    'Mercy triumphed: {npc} pardoned {target}.',
    '{npc} released {target} from their sentence.',
    'Freedom granted: {npc} pardoned {target}.',
    '{npc} chose forgiveness, pardoning {target}.',
  ],
  flee: [
    '{npc} fled the settlement, seeking safety elsewhere.',
    'Desperate, {npc} ran from their troubles.',
    '{npc} disappeared, fleeing their past.',
    'Gone: {npc} fled under cover of night.',
    '{npc} chose escape over confrontation, fleeing.',
  ],
  hide: [
    '{npc} went into hiding, avoiding danger.',
    'Shadow and silence: {npc} hid from their enemies.',
    '{npc} disappeared from sight, hiding.',
    'Fear drove {npc} to hide away.',
    '{npc} laid low, waiting for the storm to pass.',
  ],
  seek_revenge: [
    '{npc} plotted revenge against {target}.',
    'Vengeance burned in {npc}\'s heart toward {target}.',
    '{npc} swore to make {target} pay.',
    'The path of revenge: {npc} targeted {target}.',
    '{npc}\'s eyes were fixed on retribution against {target}.',
  ],
  protect: [
    '{npc} protected {target} from harm.',
    'A shield: {npc} stood between {target} and danger.',
    '{npc} defended {target} fiercely.',
    'Loyalty in action: {npc} protected {target}.',
    '{target} was safe because {npc} stood guard.',
  ],
  heal: [
    '{npc} healed {target}, easing their suffering.',
    'Medicine and care: {npc} tended to {target}.',
    '{target} recovered under {npc}\'s skilled hands.',
    '{npc} applied remedies, healing {target}.',
    'Compassion and skill: {npc} healed {target}.',
  ],
  poison: [
    '{npc} poisoned {target}\'s drink!',
    'A silent weapon: {npc} poisoned {target}.',
    '{target} fell ill after {npc}\'s poison took effect.',
    'Treachery in a cup: {npc} poisoned {target}.',
    '{npc} administered poison to {target} covertly.',
  ],
  murder: [
    '{npc} murdered {target} in cold blood!',
    'A life ended: {npc} killed {target}.',
    '{target} was slain by {npc}\'s hand.',
    'Murder! {npc} took {target}\'s life.',
    'Blood on {npc}\'s hands: {target} was murdered.',
  ],
  raise_child: [
    '{npc} spent the day raising their child.',
    'Parental duty: {npc} guided their child.',
    '{npc} nurtured the next generation.',
    'A child learned from {npc} today.',
    '{npc} taught their child the ways of the world.',
  ],
  teach: [
    '{npc} taught {target} a valuable skill.',
    'Knowledge passed from {npc} to {target}.',
    '{target} learned under {npc}\'s instruction.',
    '{npc} shared wisdom with {target}.',
    'Education: {npc} instructed {target}.',
  ],
  apprentice: [
    '{npc} took {target} as an apprentice.',
    'A new beginning: {target} apprenticed under {npc}.',
    '{npc} agreed to train {target} in their craft.',
    'Master and student: {npc} and {target} began training.',
    '{target} started their apprenticeship with {npc}.',
  ],
  join_faction: [
    '{npc} joined the {faction}.',
    'Allegiance declared: {npc} joined the {faction}.',
    '{npc} swore loyalty to the {faction}.',
    'The {faction} welcomed {npc} into their ranks.',
    '{npc} pledged themselves to the {faction}.',
  ],
  leave_faction: [
    '{npc} left the {faction}, going their own way.',
    'Broken ties: {npc} departed the {faction}.',
    '{npc} renounced their membership in the {faction}.',
    'The {faction} lost a member as {npc} left.',
    '{npc} walked away from the {faction}.',
  ],
  form_gang: [
    '{npc} formed a gang with like-minded individuals.',
    'A criminal gang coalesced around {npc}.',
    '{npc} gathered followers, forming a gang.',
    'Shadows gathered: {npc} formed a gang.',
    'The underworld grew as {npc} formed a gang.',
  ],
  strike: [
    'Workers struck! {npc} led the labor action.',
    '{npc} organized a strike, halting work.',
    'Tools down: {npc} led a strike for better conditions.',
    'The settlement trembled as {npc} called a strike.',
    '{npc} rallied workers for a strike.',
  ],
  riot: [
    'A riot erupted! {npc} was among the mob.',
    'Chaos in the streets as {npc} rioted.',
    '{npc} joined the riot, anger boiling over.',
    'The mob surged as {npc} participated in the riot.',
    'Destruction: {npc} took part in the riot.',
  ],
  run_for_office: [
    '{npc} announced their candidacy for leadership.',
    'Ambition drove {npc} to run for office.',
    '{npc} declared their intent to lead the settlement.',
    'A new candidate: {npc} entered the race.',
    '{npc} sought the people\'s mandate to lead.',
  ],
  campaign: [
    '{npc} campaigned vigorously, seeking support.',
    'Promises and handshakes: {npc} campaigned.',
    '{npc} rallied support for their cause.',
    'The campaign trail: {npc} sought votes.',
    '{npc} worked the crowds, building support.',
  ],
  embezzle: [
    '{npc} embezzled funds from the {faction}.',
    'Corruption: {npc} siphoned money from the {faction}.',
    '{npc} skimmed coin from the {faction}\'s coffers.',
    'The {faction} was robbed from within by {npc}.',
    '{npc} secretly diverted {faction} funds to their own purse.',
  ],
  gamble: [
    '{npc} gambled their coin, fortune uncertain.',
    'Dice rolled: {npc} took a chance at the gaming table.',
    '{npc} wagered coin, hoping for luck.',
    'Fortune favored {npc} at the gambling table.',
    '{npc} risked their savings on a gamble.',
  ],
  pray: [
    '{npc} knelt in prayer, seeking divine guidance.',
    'Faith sustained {npc} as they prayed.',
    '{npc} offered prayers at the shrine.',
    'Devotion: {npc} spent time in prayer.',
    '{npc} sought comfort in prayer.',
  ],
  migrate: [
    '{npc} migrated to a new district.',
    'A new home: {npc} moved to {district}.',
    '{npc} relocated, seeking fresh starts.',
    'Change of scene: {npc} migrated.',
    '{npc} left their old home behind, migrating.',
  ],
  found_business: [
    '{npc} founded a new business!',
    'Enterprise born: {npc} opened a new venture.',
    '{npc} invested in a new business in {district}.',
    'Commerce expanded as {npc} founded a business.',
    '{npc} became an entrepreneur, founding a business.',
  ],
  go_bankrupt: [
    '{npc} went bankrupt, losing everything.',
    'Ruined: {npc}\'s business collapsed.',
    'Debts overwhelmed {npc}, who went bankrupt.',
    'The crash: {npc} lost everything to bankruptcy.',
    '{npc}\'s fortune evaporated in bankruptcy.',
  ],
  host_feast: [
    '{npc} hosted a grand feast for the settlement!',
    'Music and food: {npc} threw a feast.',
    '{npc} opened their halls for a celebration.',
    'A feast! {npc} spared no expense.',
    '{npc}\'s feast brought joy to all attendees.',
  ],
  spread_rumor: [
    '{npc} spread a rumor through the settlement.',
    'Whispers: {npc} circulated a rumor.',
    '{npc}\'s rumor traveled fast through the streets.',
    'Seeds of doubt: {npc} spread a rumor.',
    '{npc} whispered tales that spread like wildfire.',
  ],
  // World events
  harvest_failure: [
    'The harvest failed! Crops withered across the Farms district.',
    'Disaster struck: a terrible harvest left the settlement hungry.',
    'Blight consumed the fields. The harvest was lost.',
    'Farmers wept as their crops failed to mature.',
    'A failed harvest sent shockwaves through the settlement.',
  ],
  plague: [
    'A plague swept through the settlement! Illness spread rapidly.',
    'Sickness took hold. The plague spared no district.',
    'Fever and cough: plague ravaged the populace.',
    'The healers were overwhelmed as plague struck.',
    'Death walked the streets as plague consumed the settlement.',
  ],
  bandit_raid: [
    'Bandits raided the settlement! Goods were stolen and people hurt.',
    'A brutal bandit raid left the settlement reeling.',
    'Outlaws descended, taking what they could by force.',
    'The bandit raid left destruction in its wake.',
    'Fear gripped the settlement as bandits struck.',
  ],
  fire: [
    'Fire broke out in the {district}! Buildings burned.',
    'Flames consumed part of the {district} district.',
    'A devastating fire swept through the {district}.',
    'Smoke rose as fire destroyed homes in {district}.',
    'The {district} district burned as fire raged.',
  ],
  festival: [
    'A festival brought joy to the settlement!',
    'Celebration filled the air as the festival began.',
    'Music, food, and laughter: the festival was a success.',
    'The settlement came together for a grand festival.',
    'Joy reigned during the festival season.',
  ],
  trade_caravan: [
    'A trade caravan arrived with exotic goods!',
    'Merchants from afar brought new wares to the settlement.',
    'The trade caravan enriched the market with rare items.',
    'New goods flowed in as the caravan arrived.',
    'The settlement buzzed with the arrival of traders.',
  ],
  immigrants: [
    'New immigrants arrived, seeking a better life.',
    'Strangers became neighbors as immigrants joined the settlement.',
    'A group of newcomers settled in the {district}.',
    'The settlement grew as immigrants found refuge here.',
    'Fresh faces appeared as immigrants arrived.',
  ],
  tax_hike: [
    'Taxes were raised! The burden on citizens increased.',
    'The leadership imposed higher taxes, causing grumbling.',
    'Coin was demanded as taxes rose across the settlement.',
    'Heavier taxes squeezed the populace.',
    'The tax collector\'s demands grew harsher.',
  ],
  flood: [
    'Flooding devastated the lower districts!',
    'Waters rose, flooding homes and fields.',
    'A great flood swept through the settlement.',
    'Rain and river combined to flood the {district}.',
    'Destruction by water: floods ravaged the settlement.',
  ],
  famine: [
    'Famine gripped the settlement. Food grew scarce.',
    'Empty bellies and desperate eyes: famine had come.',
    'The granaries ran dry as famine took hold.',
    'Starvation loomed as famine struck the settlement.',
    'Famine: the cruelest visitor of all.',
  ],
  foreign_war: [
    'Foreign war threatened! Conscription orders went out.',
    'The drums of war echoed. Citizens were drafted.',
    'War came calling, demanding soldiers from the settlement.',
    'Young men and women were drafted for the foreign war.',
    'The shadow of war fell across the settlement.',
  ],
  rare_festival: [
    'A once-in-a-generation festival brought wonder to all!',
    'The rare festival occurred, a spectacle of magnificence.',
    'Legends spoke of this festival. Now it was reality.',
    'The rare festival transformed the settlement into paradise.',
    'A miraculous festival blessed the settlement.',
  ],
};

// ============================================================
// SECTION 3: STORY PATTERNS
// ============================================================

export interface StoryPattern {
  id: string;
  name: string;
  description: string;
  check: (state: any) => StoryMatch | null;
}

export interface StoryMatch {
  pattern: string;
  title: string;
  description: string;
  roles: { role: string; npcId: number }[];
  approaches: string[];
  causalChain: string[];
  tension: number;
}

// ============================================================
// SECTION 4: WILDLIFE CREATURES (generated from elements)
// ============================================================

export interface Creature {
  id: number;
  name: string;
  elements: string[];
  threat: number; // 0..1
  habitat: string;
  tags: string[];
}

export const CREATURE_TEMPLATES = [
  { name: 'Shadow Wolf', elements: ['head_wolf', 'fur_short', 'night_vision', 'pack_instinct', 'keen_smell', 'forest_camouflage'], threat: 0.6, habitat: 'forest' },
  { name: 'Iron Boar', elements: ['head_boar', 'hide_thick', 'tusk', 'territorial', 'fight_first', 'forest_camouflage'], threat: 0.5, habitat: 'forest' },
  { name: 'Venom Serpent', elements: ['head_serpent', 'scales_fine', 'venom_gland', 'ambush', 'thermal_sense', 'desert_adapted'], threat: 0.4, habitat: 'desert' },
  { name: 'Great Eagle', elements: ['head_eagle', 'body_avian', 'limb_wing_large', 'keen_hearing', 'depth_perception', 'cliff_dwelling'], threat: 0.3, habitat: 'mountain' },
  { name: 'Swamp Lurker', elements: ['body_aquatic', 'slime_coat', 'ambush', 'swamp_adapted', 'night_vision', 'venom_gland'], threat: 0.5, habitat: 'swamp' },
  { name: 'Cave Bear', elements: ['head_lion', 'fur_long', 'body_massive', 'bone_dense', 'cave_dwelling', 'territorial'], threat: 0.8, habitat: 'cave' },
  { name: 'Plague Rat', elements: ['head_rodent', 'fur_short', 'body_small', 'hoarding', 'urban', 'scavenging'], threat: 0.1, habitat: 'urban' },
  { name: 'River Drake', elements: ['head_serpent', 'scales_plate', 'body_aquatic', 'fire_gland', 'freshwater', 'territorial'], threat: 0.7, habitat: 'river' },
  { name: 'Harvest Spider', elements: ['body_arachnid', 'chitin', 'silk_spinner', 'web_building', 'ambush', 'grassland'], threat: 0.2, habitat: 'fields' },
  { name: 'Storm Hawk', elements: ['head_eagle', 'body_avian', 'limb_wing_large', 'feathers', 'far_field_vision', 'coastal'], threat: 0.3, habitat: 'coast' },
  { name: 'Night Stalker', elements: ['head_feline', 'fur_short', 'night_vision', 'ambush', 'stealth', 'forest_camouflage'], threat: 0.6, habitat: 'forest' },
  { name: 'Thornback Lizard', elements: ['head_serpent', 'spines', 'scales_plate', 'heat_resistant', 'desert_adapted', 'freeze_response'], threat: 0.3, habitat: 'desert' },
  { name: 'Mire Crawler', elements: ['body_insectoid', 'mandible', 'chitin', 'swamp_adapted', 'scavenging', 'burrowing'], threat: 0.4, habitat: 'swamp' },
  { name: 'Frost Wyrm', elements: ['head_serpent', 'body_massive', 'scales_plate', 'cold_resistant', 'ice_gland', 'cave_dwelling'], threat: 0.9, habitat: 'tundra' },
  { name: 'Ember Fox', elements: ['head_canine', 'fur_short', 'body_small', 'curious', 'nocturnal', 'temperate'], threat: 0.1, habitat: 'forest' },
  { name: 'Bone Crab', elements: ['body_crustacean', 'claw_hooked', 'chitin', 'coastal', 'scavenging', 'armor'], threat: 0.3, habitat: 'coast' },
  { name: 'Whisper Bat', elements: ['body_avian', 'limb_wing_small', 'echolocation', 'nocturnal', 'cave_dwelling', 'body_small'], threat: 0.1, habitat: 'cave' },
  { name: 'Razor Beetle', elements: ['body_insectoid', 'mandible', 'chitin', 'flight', 'forest_camouflage', 'hoarding'], threat: 0.2, habitat: 'forest' },
  { name: 'Dune Scorpion', elements: ['body_arachnid', 'stinger', 'venom_gland', 'desert_adapted', 'ambush', 'nocturnal'], threat: 0.5, habitat: 'desert' },
  { name: 'Wild Ox', elements: ['head_horned', 'body_quadruped', 'hoof', 'hide_thick', 'herd_following', 'grassland'], threat: 0.4, habitat: 'plains' },
];

// ============================================================
// SECTION 5: NAME GENERATION DATA
// ============================================================

export const FIRST_SYLLABLES = [
  'Mar', 'El', 'Thar', 'Bren', 'Sil', 'Cor', 'Dra', 'Fen', 'Gor', 'Hal',
  'Isk', 'Jor', 'Kel', 'Lir', 'Mor', 'Nar', 'Orin', 'Pir', 'Quen', 'Rav',
  'Sor', 'Tav', 'Ul', 'Ves', 'Wyn', 'Xan', 'Yor', 'Zel', 'Ald', 'Bri',
  'Cas', 'Dor', 'Eva', 'Fin', 'Gre', 'Hel', 'Iva', 'Jas', 'Kor', 'Lun',
  'Mir', 'Nes', 'Ora', 'Pal', 'Ren', 'Sia', 'Tor', 'Uma', 'Val', 'Wren'
];

export const LAST_SYLLABLES = [
  'dask', 'vell', 'thorn', 'wick', 'mere', 'fell', 'burn', 'dale', 'stone', 'hart',
  'crest', 'wood', 'vale', 'ridge', 'brook', 'marsh', 'glen', 'ford', 'holm', 'cliff',
  'shaw', 'moor', 'heath', 'field', 'lake', 'wind', 'ash', 'oak', 'pine', 'elm',
  'creek', 'haven', 'port', 'gate', 'wall', 'tower', 'keep', 'mill', 'cross', 'bridge',
  'hill', 'peak', 'down', 'stead', 'worth', 'bury', 'ton', 'ham', 'ley', 'by'
];

export const DISTRICTS = ['Market', 'Farms', 'Docks', 'Old Quarter'] as const;
export type District = typeof DISTRICTS[number];

export const JOBS = [
  'farmer', 'fisher', 'merchant', 'guard', 'craftsman', 'healer', 'scholar',
  'thief', 'sailor', 'laborer', 'brewer', 'tailor', 'smith', 'hunter',
  'priest', 'noble', 'servant', 'herbalist', 'miner', 'carpenter'
] as const;

export const FACTIONS = ['Guards', 'Merchant Guild', 'Farmer Collective', 'Criminal Underground'] as const;
export type Faction = typeof FACTIONS[number];
